version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 255845675097.dkr.ecr.ca-central-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t singh-app .
      - docker tag singh-app:latest 255845675097.dkr.ecr.ca-central-1.amazonaws.com/singh-app:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 255845675097.dkr.ecr.ca-central-1.amazonaws.com/singh-app:latest
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"Singh-container","imageUri":"255845675097.dkr.ecr.ca-central-1.amazonaws.com/singh-app:latest"}]' > imagedefinitions.json
      - echo "imagedefinitions.json created successfully."
      - echo "Build completed on $(date)"
      
artifacts:
  files:
    - imagedefinitions.json
